git remote add rakhele         https://github.com/rakhele/spbetu_os_2020_8382.git         # Рочева
git remote add sinelnikovmaxim https://github.com/sinelnikovmaxim/spbetu_os_2020_8382.git # Синельников
git remote add snchz29         https://github.com/snchz29/spbetu_os_2020_8382.git         # Терехов
git remote add AhimasYD        https://github.com/AhimasYD/spbetu_os_2020_8382.git        # Янкин
git remote add pajecawa        https://github.com/pajecawav/spbetu_os_2020_8382.git       # Колногоров
git remote add LangerKrieg     https://github.com/LangerKrieg/spbetu_os_2020_8382.git     # Наконечная
git remote add PavelChernitsyn https://github.com/PavelChernitsyn/spbetu_os_2020_8382.git # Черницын
git remote add Pavel-by        https://github.com/Pavel-by/spbetu_os_2020_8382.git        # Мирончик
git remote add inoriin         https://github.com/inoriin/spbetu_os_2020_8382.git         # Чирков
git remote add ephemerno       https://github.com/ephemerno/spbetu_os_2020_8382.git       # Ефимова
